### ISSUE TITLE
mvn build error on bcprov-jdk15on 

### ISSUE THREAD

**Issue by ygokirmak** [spring-cloud-samples/configserver#14]
Hi,

I am getting error while trying to start project. 
it can not found dependency http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar

I can work on and try to solve this problem
can you give me some advice?

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Config Server 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.3.2.RELEASE:run (default-cli) @ configserver >>>
Downloading: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
Downloading: http://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.603s
[INFO] Finished at: Wed Feb 17 08:57:07 EET 2016
[INFO] Final Memory: 18M/209M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project configserver: Could not resolve dependencies for project org.demo:configserver:jar:0.0.1-SNAPSHOT: Could not transfer artifact org.bouncycastle:bcprov-jdk15on:jar:1.47 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project configserver: Could not resolve dependencies for project org.demo:configserver:jar:0.0.1-SNAPSHOT: Could not transfer artifact org.bouncycastle:bcprov-jdk15on:jar:1.47 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar. Return code is: 409 , ReasonPhrase:Conflict.
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.demo:configserver:jar:0.0.1-SNAPSHOT: Could not transfer artifact org.bouncycastle:bcprov-jdk15on:jar:1.47 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar. Return code is: 409 , ReasonPhrase:Conflict.
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
	... 26 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not transfer artifact org.bouncycastle:bcprov-jdk15on:jar:1.47 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar. Return code is: 409 , ReasonPhrase:Conflict.
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
	... 27 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.bouncycastle:bcprov-jdk15on:jar:1.47 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar. Return code is: 409 , ReasonPhrase:Conflict.
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	... 28 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.bouncycastle:bcprov-jdk15on:jar:1.47 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar. Return code is: 409 , ReasonPhrase:Conflict.
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar. Return code is: 409 , ReasonPhrase:Conflict.
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:945)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
	... 4 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by spencergibb** [comment]
Must be a network connection issue on your side. It's located in maven central: http://search.maven.org/#artifactdetails%7Corg.bouncycastle%7Cbcprov-jdk15on%7C1.47%7Cjar
